name: "Prateek Tripathi"
contact:
  email: "ptripathi@mt.iitr.ac.in"
  phone: "+91 7905109067"
  location: "Banglore, India"
experience:
  - company: "JPMorgan Chase & Co."
    role: "Software Engineer"
    location: "Banglore, India"
    start_date: "July 2022"
    end_date: "Present"
    details:
      - "Managed cross-functional team of 10 in 3 locations (Palo Alto, Austin and New York), ranging from entry-level analysts to vice presidents, and collaborated with business development, data analysis, operations and marketing"
      - "Launched Miami office with lead Director and recruited and managed new team of 10 employees; grew office revenue by 200% in first nine months (representing 20% of company revenue)"
      - "Designed training and peer-mentoring programs for the incoming class of 25 analysts in 2017; reduced onboarding time for new hires by 50%"
      - "Achieved $200K reduction in department overspend by establishing ROI metrics and budget controls to improve prioritisation of the $4MM department budget"
  - company: "Yojak"
    role: "Backend Intern"
    location: "Remote"
    start_date: "Dec 2021"
    end_date: "Jan 2022"
    details:
      - "Spearheaded a major pricing restructure by redirecting focus on consumer willingness to pay instead of product cost; implemented a three-tiered pricing model which increased average sale 35% and margin 12%"
      - "Promoted within 12 months due to strong performance and organizational impact (1 year ahead of schedule)"
      - "Identified steps to reduce return rates by 10% resulting in an eventual $75k cost savings"
  - company: "JP Morgan Chase & Co."
    role: "Software Engineer Intern"
    location: "Banglore, India / Remote"
    start_date: "May 2021"
    end_date: "Jun 2021"
    details:
      - "Analyzed data from 25000 monthly active users and used outputs to guide marketing and product strategies; increased app engagement time by 2x, 30% decrease in drop off rate, and 3x shares on social media"
      - "Drove redevelopment of internal tracking system in use by 125 employees, resulting in 20+ new features, reduction of 20% in save/load time and 15% operation time"
projects:
  - name: "Steorological Projections"
    link: "https://github.com/c0deek/btp"
    link_type: "Github"
  - name: "config2resume"
    link: "https://github.com/c0deek/config2resume"
    link_type: "Github"
education:
  history:
    - institution: "IIT Roorkee"
      degree: "B.Tech"
      branch: "Metallurgical & Materials Engineering"
      graduation_year: "2022"
      cgpa: "8.6"
    - institution: "K.V.2, Armapur, Kanpur"
      degree: "XII"
      board: "CBSE (PCM)"
      percentage: "96.2%"
      graduation_year: "2018"
  achievements:
    - "Best B.Tech Project (Steorological Projections)"
    - "Top 1.5 % in CBSE Class 12"
other:
  technical_skills:
    - "R"
    - "Visual Basic"
    - "Microsoft SQL Server"
    - "Tableau"
    - "SQL"
    - "Financial Modeling"
    - "Python"
  certifications:
    - "Certified Scrum Master"
    - "Passed Resume Worded examinations"
  languages:
    - "English (native)"
    - "Spanish (fluent)"
    - "Chinese (intermediate)"
